service: orders-service

custom:
  tableName: "orders-table-${self:provider.stage}"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - lambda:InvokeFunction
        - dynamodb:ListStreams
      Resource:
        - "*" # TODO: Specify resources at a granular level. But what's the pattern/syntax???
  environment:
    ORDERS_TABLE: ${self:custom.tableName}
    PAYMENTS_SERVICE_FUNCTION: payments-service-dev-handler
    WEBSOCKET_SERVICE_FUNCTION: websocket-service-dev-handler

functions:
  triggerStream:
    handler: handler.triggerStream
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - OrdersDynamoDBTable
              - StreamArn
  handler:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true # <-- CORS!
      - http:
          path: /
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - authority
              - cache-control
              - pragma
              - user-agent
      - http:
          path: /
          method: put
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - authority
              - cache-control
              - pragma
              - user-agent

resources:
  Resources:
    OrdersDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
        KeySchema:
          - AttributeName: orderId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
        StreamSpecification:
          StreamViewType: NEW_IMAGE
